apiVersion: v1
kind: Secret
metadata:
  name: products-api-secret

type: Opaque
stringData:
  application.properties: |-
    spring.jpa.database=POSTGRESQL
    spring.datasource.platform=postgres
    spring.datasource.url=jdbc:postgresql://products-db-0.products-db:5432/postgres
    spring.datasource.username=postgres
    spring.datasource.password=GroupH4ck@thon
