apiVersion: v1
kind: Secret
metadata:
  name: stock-api-secret

type: Opaque
stringData:
  POSTGRES_CONNECTION_STRING: "host=products-db port=5432 user=postgres password=GroupH4ck@thon dbname=postgres sslmode=disable"
