apiVersion: v1
kind: Service
metadata:
  name: {{ include "widgetario.fullname" . }}-products-db
spec:
  ports:
    - port: 5432
      targetPort: postgres
  selector:
    app: {{ include "widgetario.fullname" . }}-products-db
  type: ClusterIP
  clusterIP: None
