apiVersion: v1
kind: Secret
metadata:
  name: {{ include "widgetario.fullname" . }}-products-api-secret
type: Opaque
stringData:
  application.properties: |-
    spring.jpa.database=POSTGRESQL
    spring.datasource.platform=postgres
    spring.datasource.url=jdbc:postgresql://{{ include "widgetario.fullname" . }}-products-db-0.{{ include "widgetario.fullname" . }}-products-db:5432/postgres
    spring.datasource.username=postgres
    spring.datasource.password={{ .Values.productsDb.password | quote }}
