apiVersion: v1
kind: Service
metadata:
  name: {{ include "widgetario.fullname" . }}-stock-api
spec:
  ports:
    - port: 8080
      targetPort: http
  selector:
    app: {{ include "widgetario.fullname" . }}-stock-api
  type: ClusterIP
