apiVersion: v1
kind: Secret
metadata:
  name: {{ include "widgetario.fullname" . }}-stock-api-secret
type: Opaque
stringData:
  POSTGRES_CONNECTION_STRING: >-
    host={{ include "widgetario.fullname" . }}-products-db-0.{{ include "widgetario.fullname" . }}-products-db
    port=5432 user=postgres password={{ .Values.stockApi.database.password }}
    dbname=postgres sslmode=disable