apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "widgetario.fullname" . }}-web
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "widgetario.fullname" . }}-web
  template:
    metadata:
      labels: 
        app: {{ include "widgetario.fullname" . }}-web
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: app
          image: {{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}
          ports:
            - containerPort: 80
              name: http
          envFrom:
            - secretRef:
                name: {{ include "widgetario.fullname" . }}-web-secret
            - configMapRef:
                name: {{ include "widgetario.fullname" . }}-web-config
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 3
          resources:
{{- if .Values.web.resources.enabled }}
            requests:
              cpu: {{ .Values.web.resources.requests.cpu }}
              memory: {{ .Values.web.resources.requests.memory }}
            limits:
              cpu: {{ .Values.web.resources.limits.cpu }}
              memory: {{ .Values.web.resources.limits.memory }}
{{- end }}
      terminationGracePeriodSeconds: 30
