apiVersion: v1
kind: Secret
metadata:
  name: web-secret

type: Opaque
stringData:
  api.json: |-
    {
      "Widgetario": {
        "ProductsApi": {
          "Url": "http:/api.widgetario.local/products"
        },
      }
    }
